#!/bin/bash

usage() {
    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
    printf "\nWhere:"
    printf "\n\t-c indicates clean first"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-p indicates skip package creation step"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

CLEAN=
DRAFT=
PACKAGE=1
BRANCH="main"
while getopts "b:cdpu" flag; do
    case $flag in
        b)
            BRANCH="${OPTARG}"
            ;;
        c)
            CLEAN=1
            ;;
        d)
            DRAFT="--draft"
            ;;
        p)
            PACKAGE=
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

if [ -f VERSION ]; then
  source VERSION
else
  echo "ERROR: missing VERSION"
  exit 1
fi

ANNO="Corrade Control Panel release, version ${VERSION}"

if [ -f ${HOME}/.mrprivate ]; then
  source ${HOME}/.mrprivate
fi

make clean
make
[ -f CorradeControlPanel.zip ] && [ -f CorradeControlPanel.lslo ] || {
  echo "ERROR: cannot locate CorradeControlPanel.zip"
  exit 1
}

#tar cf - Examples/*/*.txt Examples/*/*.lslo Examples/*.lslo | gzip -9 > Examples-${VERSION}.tar.gz
#        Examples-${VERSION}.tar.gz \
tar cf - CorradeControlPanel.lslo \
         Configuration \
         LICENSE \
         VERSION | gzip -9 > CorradeControlPanel-${VERSION}.tar.gz

gh release create v${VERSION} ${DRAFT} \
                  --title "${ANNO}" \
                  --target "${BRANCH}" \
                  --notes-file Release_Notes.md \
                  CorradeControlPanel.lslo \
                  Configuration \
                  header.lsl \
                  CorradeControlPanel-${VERSION}.tar.gz \
                  CorradeControlPanel.zip

git fetch --tags origin
#rm -f Examples-${VERSION}.tar.gz CorradeControlPanel-${VERSION}.tar.gz
rm -f CorradeControlPanel-${VERSION}.tar.gz
make clean
